name: dubai_app_studio
description: "technical assessment for Dubai App Studio company"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  get_it: ^7.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
